language: python
python:
  - "2.7"
before_install:
  - openssl aes-256-cbc -K $encrypted_d78a7203a7b0_key -iv $encrypted_d78a7203a7b0_iv -in build/github_deploy_key.enc -out build/github_deploy_key -d
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git config --global push.default simple
  - git remote set-url origin git://git@github.com/christianpanton/visitationszone.git
install: "pip install -r requirements.txt"
script: python build/build.py
after_success:
   $(npm bin)/set-up-ssh --key "$encrypted_d78a7203a7b0_key" \
                             --iv "$encrypted_d78a7203a7b0_iv" \
                             --path-encrypted-key "build/github_deploy_key.enc"

  - git add zones/*
  - git add zones.json
  - git commit --message "Travis build $TRAVIS_BUILD_NUMBER"
  - git push origin master